"""Human-readable explanation model."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Explanation:
    """Structured explanation generated by PlantMind."""

    title: str
    summary: str
    details: tuple[str, ...] = ()