"""Engineering reasoning report."""

from __future__ import annotations

from dataclasses import dataclass

from app.services.reasoning.explanation import Explanation
from app.services.reasoning.result import ReasoningResult


@dataclass(frozen=True, slots=True)
class ReasoningReport:
    """Final engineering report generated by PlantMind."""

    result: ReasoningResult
    explanation: Explanation